// Never Forget: Comments can "lie", but code not so much ;P
//----------------------------------------------------------//
// Contains internal abstract code that is project specific //
//----------------------------------------------------------//


// Purpose:
// -------------------------------------------------------------------------
// Parameters:|
// ============
// typeNumber  	->  
DEFINE_DIMORPHIC_FUNCTION ~CONCATENATE_AND_EXTRACT_STRREFS~
	INT_VAR
		typeNumber 		= "-1"
	STR_VAR
		arrayName	= ~!_NULL~
BEGIN
	

END // End of "READ_ITEMCATEGORY_ID_FROM_IDS"